
CREATE TABLE OAUTH_CLIENT_DETAILS  (
    CLIENT_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    RESOURCE_IDS VARCHAR(255),
    CLIENT_SECRET VARCHAR(255),
    SCOPE VARCHAR(255),
    AUTHORIZED_GRANT_TYPES VARCHAR(255),
    WEB_SERVER_REDIRECT_URI VARCHAR(255),
    AUTHORITIES VARCHAR(255),
    ACCESS_TOKEN_VALIDITY BIGINT,
    REFRESH_TOKEN_VALIDITY BIGINT,
    ADDITIONAL_INFORMATION VARCHAR(4096),
    AUTOAPPROVE VARCHAR(255)
) ;

